version: '3.2'

# Complementary services, not part of geOrchestra core.
# They are made to ease your life as a developer.
# **NOT** production ready !

services:
  georchestra.mydomain.org:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
      #- "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/ssl:/etc/traefik/ssl/
      - /dev/null:/traefik.toml
    # commande de production déplacée dans docker-compose.geosync-prod.yml
    #command: --web --docker --logLevel=INFO --docker.domain='mydomain.org' --docker.exposedbydefault='false' --docker.watch --entryPoints='Name:https Address::443 TLS:/etc/traefik/ssl/georchestra.mydomain.org.crt,/etc/traefik/ssl/georchestra.mydomain.org.key' --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --defaultentrypoints=http,https
    restart: always

  proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sp"
      # label de production déplacé dans docker-compose.geosync-prod.yml
      #- "traefik.frontend.rule=Host:georchestra.mydomain.org"
      - "traefik.frontend.passHostHeader=true"
    restart: always

  smtp:
    build: docker/smtp/smtp-sink
    image: camptocamp/smtp-sink:latest
    restart: always

  geodata:
    build: docker/ssh_data
    image: georchestra/ssh_data:latest
    environment:
      - TZ=Europe/Paris
    ports:
      - "2222:22"
    volumes:
      #- geoserver_geodata:/mnt/geoserver_geodata
      - /docker/georchestra/geoserver_geodata:/mnt/geoserver_geodata
    restart: always

  geosync:
    build: geosync
    image: geosync/geosync
    depends_on:
      - ldap
      - database
      - geoserver
      - geonetwork
    environment:
      - TZ=Europe/Paris
      # variables de production déplacées dans docker-compose.geosync-prod.yml
      #- SERVER_URL=https://georchestra.mydomain.org
      #- OCL_URL=https://owncloud.mydomain.org
    volumes:
      - /docker/georchestra/georchestra_ouvert:/home/georchestra-ouvert
      #- /docker/georchestra/geosync_test_ouvert:/mnt/geosync_ouvert/owncloudsync
      - /docker/georchestra/georchestra_restreint:/home/georchestra-restreint
      #- /docker/georchestra/geosync_test_restreint:/mnt/geosync_restreint/owncloudsync
    restart: always

