version: '3.2'

volumes:
  postgresql_data:
  ldap_data:
  ldap_config:
  geoserver_datadir:
  geoserver_geodata:
  geoserver_tiles:
  mapfishapp_uploads:
  extractorapp_extracts:
  geonetwork_datadir:
  geosync_ouvert:
  geosync_restreint:

services:
  database:
    image: geosync/database
    build: postgresql.geosync
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=georchestra
      - POSTGRES_PASSWORD=georchestra
    volumes:
      #- postgresql_data:/var/lib/postgresql/data
      - /docker/georchestra/postgresql_data:/var/lib/postgresql/data
    restart: always

  ldap:
    image: geosync/ldap
    build: ldap.geosync
    environment:
      - SLAPD_DC_STRING=dc=georchestra,dc=org
      - SLAPD_ORGANISATION=georchestra
      - SLAPD_DOMAIN=georchestra.org
      - SLAPD_PASSWORD=secret
      - SLAPD_ADDITIONAL_MODULES=groupofmembers
      - AD_DOMAIN=umrthema.univ-fcomte.fr
      - AD_DC_STRING=dc=umrthema,dc=univ-fcomte,dc=fr
      - AD_SERVER=thema-serv3.umrthema.univ-fcomte.fr
      # - AD_PASSWORD dans docker-compose.geosync-prod.yml

    volumes:
      #- ldap_data:/var/lib/ldap
      - /docker/georchestra/ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap
    extra_hosts:
      - "thema-serv3.umrthema.univ-fcomte.fr:172.20.74.170"
    restart: always

  geoserver:
    image: geosync/geoserver
    build: geoserver/webapp/src/docker.geosync
    #image: georchestra/geoserver
    #build: geoserver/webapp/src/docker
    depends_on:
      - ldap
    volumes:
      #- geoserver_datadir:/mnt/geoserver_datadir
      - /docker/georchestra/geoserver_datadir:/mnt/geoserver_datadir
      #- geoserver_geodata:/mnt/geoserver_geodata
      - /docker/georchestra/geoserver_geodata:/mnt/geoserver_geodata
      - geoserver_tiles:/mnt/geoserver_tiles
    environment:
      - TZ=Europe/Paris
      #- SERVER_URL=https://georchestra-docker.umrthema.univ-fcomte.fr
      #- SERVER_URL=https://georchestra-test.umrthema.univ-fcomte.fr
      #- SERVER_URL=https://georchestra-dev.umrthema.univ-fcomte.fr
      - SERVER_URL=https://georchestra-mshe.univ-fcomte.fr
      - XMS=256M
      - XMX=8G
    extra_hosts:
      - "georchestra-dev.umrthema.univ-fcomte.fr:172.20.74.138"
      - "georchestra-test.umrthema.univ-fcomte.fr:172.20.74.83"
      - "georchestra-docker.umrthema.univ-fcomte.fr:172.20.74.124"
      - "georchestra-mshe.univ-fcomte.fr:193.55.67.144"
    restart: always

  proxy:
    image: georchestra/security-proxy:latest
    depends_on:
      - ldap
      - database
    volumes:
      - /etc/georchestra:/etc/georchestra
    environment:
      - XMS=256M
      - XMX=1G
    extra_hosts:
      - "georchestra-dev.umrthema.univ-fcomte.fr:172.20.74.138"
      - "georchestra-test.umrthema.univ-fcomte.fr:172.20.74.83"
      - "georchestra-docker.umrthema.univ-fcomte.fr:172.20.74.124"
      - "georchestra-mshe.univ-fcomte.fr:193.55.67.144"
    restart: always

  cas:
    image: georchestra/cas:latest
    depends_on:
      - ldap
    volumes:
      - /etc/georchestra:/etc/georchestra
    environment:
      - XMS=256M
      - XMX=1G
    restart: always

  mapfishapp:
    image: georchestra/mapfishapp:latest
    depends_on:
      - database
    volumes:
      - /etc/georchestra:/etc/georchestra
      - mapfishapp_uploads:/mnt/mapfishapp_uploads
    environment:
      - XMS=256M
      - XMX=2G
    restart: always

  extractorapp:
    image: georchestra/extractorapp:latest
    depends_on:
      - database
    volumes:
      - /etc/georchestra:/etc/georchestra
      - extractorapp_extracts:/mnt/extractorapp_extracts
    environment:
      - XMS=256M
      - XMX=2G
    restart: always

  header:
    image: georchestra/header:latest
    volumes:
      - /etc/georchestra:/etc/georchestra
    environment:
      - XMS=256M
      - XMX=512M
    restart: always

  ldapadmin:
    image: georchestra/ldapadmin:latest
    depends_on:
      - ldap
      - database
    volumes:
      - /etc/georchestra:/etc/georchestra
    environment:
      - XMS=256M
      - XMX=1G
    restart: always

  geonetwork:
    image: georchestra/geonetwork:3-latest
    depends_on:
      - ldap
      - database
    volumes:
      - /etc/georchestra:/etc/georchestra
      - geonetwork_datadir:/mnt/geonetwork_datadir
      #- /docker/georchestra/geoserver_geodata:/mnt/geoserver_geodata
      - type : volume
        source : geosync_ouvert
        target : /mnt/geosync_ouvert
    environment:
      - XMS=256M
      - XMX=6G
    extra_hosts:
      - "georchestra-dev.umrthema.univ-fcomte.fr:172.20.74.138"
      - "georchestra-test.umrthema.univ-fcomte.fr:172.20.74.83"
      - "georchestra-docker.umrthema.univ-fcomte.fr:172.20.74.124"
      - "georchestra-mshe.univ-fcomte.fr:193.55.67.144"
    restart: always

  analytics:
    image: georchestra/analytics:latest
    depends_on:
      - database
    volumes:
      - /etc/georchestra:/etc/georchestra
    environment:
      - XMS=256M
      - XMX=1G
    restart: always


