version: '3'

# variables d'environnement avec secrets

services:

  ldap:
    environment:
      - AD_PASSWORD=ad_secret_password

  geosync:
    environment:
      - OPEN_USER_DAVPASS=ocl_user_password
      - RSCT_USER_DAVPASS=ocl_user_password

