version: '3.2'

# variables d'environnement avec secrets

services:

  ldap:
    environment:
      - AD_PASSWORD=

  geosync:
    environment:
      - OPEN_USER_DAVPASS=Lesoleilauzenith
      - RSCT_USER_DAVPASS=Lesoleilauzenith

