version: '3'

volumes:
  geowebcache_tiles:


services:

  # standalone geowebcache:
  geowebcache:
    image: georchestra/geowebcache:latest
    volumes:
      - geowebcache_tiles:/mnt/geowebcache_tiles
      - /etc/georchestra:/etc/georchestra
    environment:
      - XMS=1G
      - XMX=2G

  # simple catalog application (csw frontend)
  catalogapp:
    image: georchestra/catalogapp:latest
    volumes:
      - /etc/georchestra:/etc/georchestra
    environment:
      - XMS=256M
      - XMX=512M

  # downloadform services (disabled by default)
  downloadform:
    image: georchestra/downloadform:latest
    volumes:
      - /etc/georchestra:/etc/georchestra
    environment:
      - XMS=256M
      - XMX=512M

  # atlas printing services, eventually queried by the mapfishapp atlas addon
  atlas:
    image: georchestra/atlas:latest
    volumes:
      - /etc/georchestra:/etc/georchestra
    environment:
      - XMS=512M
      - XMX=2G
