version: '2'
services:
  ldap:
    image: georchestra/ldap
    build: ./
    environment:
      - SLAPD_DOMAIN=georchestra.org
      - SLAPD_ORGANIZATION=georchestra
      - SLAPD_PASSWORD=secret
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap
    ports:
      - '3899:389'
