version: '3'

volumes:
  ldap_data_test:
  ldap_config_test:

services:
  ldap:
    image: georchestra/ldap
    build: ./
    environment:
      - SLAPD_DOMAIN=georchestra.org
      - SLAPD_ORGANIZATION=georchestra
      - SLAPD_PASSWORD=secret
      - SLAPD_ADDITIONAL_MODULES=groupofmembers
    volumes:
      - ldap_data_test:/var/lib/ldap
      - ldap_config_test:/etc/ldap
    ports:
      - '10389:389'
